--------------------------------------------------------------------------------
--- Generated exports map for ./
-- @module test-exports-lib.code.exports
-- This file is a part of le-tools library
-- Copyright (c) le-tools authors (see file `COPYRIGHT` for the license)
--------------------------------------------------------------------------------
-- WARNING! Do not change manually!
--          Generated by list-exports.
--------------------------------------------------------------------------------

return
{
  simple_symb1 = { { "./simple.lua", w = 500 } };
  weights_alias_symb1 = { { "./weights_alias.lua", w = 123 } };
  weights_symb1 = { { "./weights.lua", w = 15 } };
  weights_symb2 = { { "./weights.lua", w = 123 } };
}
